package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CattleAuctionpun generated by hbm2java
 */
@Entity
@Table(name = "cattle_auctionpun", catalog = "farm")
public class CattleAuctionpun implements java.io.Serializable {

	private Integer no;
	private CattleDetails cattleDetails;
	private Integer CId;
	private Integer lot;
	private String bw;
	private String ww;
	private String yw;
	private String milk;
	private String weight;
	private String high;
	private String SPrice;
	private String grandfather;
	private String grandmother;
	private String grandfather2;
	private String grandmother2;

	public CattleAuctionpun() {
	}

	public CattleAuctionpun(CattleDetails cattleDetails) {
		this.cattleDetails = cattleDetails;
	}

	public CattleAuctionpun(CattleDetails cattleDetails, Integer CId, Integer lot, String bw, String ww, String yw,
			String milk, String weight, String high, String SPrice, String grandfather, String grandmother,
			String grandfather2, String grandmother2) {
		this.cattleDetails = cattleDetails;
		this.CId = CId;
		this.lot = lot;
		this.bw = bw;
		this.ww = ww;
		this.yw = yw;
		this.milk = milk;
		this.weight = weight;
		this.high = high;
		this.SPrice = SPrice;
		this.grandfather = grandfather;
		this.grandmother = grandmother;
		this.grandfather2 = grandfather2;
		this.grandmother2 = grandmother2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "No", unique = true, nullable = false)
	public Integer getNo() {
		return this.no;
	}

	public void setNo(Integer no) {
		this.no = no;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cattle_details_No", nullable = false)
	public CattleDetails getCattleDetails() {
		return this.cattleDetails;
	}

	public void setCattleDetails(CattleDetails cattleDetails) {
		this.cattleDetails = cattleDetails;
	}

	@Column(name = "c_id")
	public Integer getCId() {
		return this.CId;
	}

	public void setCId(Integer CId) {
		this.CId = CId;
	}

	@Column(name = "lot")
	public Integer getLot() {
		return this.lot;
	}

	public void setLot(Integer lot) {
		this.lot = lot;
	}

	@Column(name = "bw", length = 50)
	public String getBw() {
		return this.bw;
	}

	public void setBw(String bw) {
		this.bw = bw;
	}

	@Column(name = "ww", length = 50)
	public String getWw() {
		return this.ww;
	}

	public void setWw(String ww) {
		this.ww = ww;
	}

	@Column(name = "yw", length = 50)
	public String getYw() {
		return this.yw;
	}

	public void setYw(String yw) {
		this.yw = yw;
	}

	@Column(name = "milk", length = 50)
	public String getMilk() {
		return this.milk;
	}

	public void setMilk(String milk) {
		this.milk = milk;
	}

	@Column(name = "weight", length = 50)
	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	@Column(name = "high", length = 45)
	public String getHigh() {
		return this.high;
	}

	public void setHigh(String high) {
		this.high = high;
	}

	@Column(name = "s_price", length = 45)
	public String getSPrice() {
		return this.SPrice;
	}

	public void setSPrice(String SPrice) {
		this.SPrice = SPrice;
	}

	@Column(name = "grandfather", length = 45)
	public String getGrandfather() {
		return this.grandfather;
	}

	public void setGrandfather(String grandfather) {
		this.grandfather = grandfather;
	}

	@Column(name = "grandmother", length = 45)
	public String getGrandmother() {
		return this.grandmother;
	}

	public void setGrandmother(String grandmother) {
		this.grandmother = grandmother;
	}

	@Column(name = "grandfather2", length = 45)
	public String getGrandfather2() {
		return this.grandfather2;
	}

	public void setGrandfather2(String grandfather2) {
		this.grandfather2 = grandfather2;
	}

	@Column(name = "grandmother2", length = 45)
	public String getGrandmother2() {
		return this.grandmother2;
	}

	public void setGrandmother2(String grandmother2) {
		this.grandmother2 = grandmother2;
	}

}
