package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CattleAuctionpunHasFestivity generated by hbm2java
 */
@Entity
@Table(name = "cattle_auctionpun_has_festivity", catalog = "farm")
public class CattleAuctionpunHasFestivity implements java.io.Serializable {

	private CattleAuctionpunHasFestivityId id;

	public CattleAuctionpunHasFestivity() {
	}

	public CattleAuctionpunHasFestivity(CattleAuctionpunHasFestivityId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cattleAuctionpunNo", column = @Column(name = "cattle_auctionpun_No", nullable = false)),
			@AttributeOverride(name = "festivityNo", column = @Column(name = "festivity_No", nullable = false)) })
	public CattleAuctionpunHasFestivityId getId() {
		return this.id;
	}

	public void setId(CattleAuctionpunHasFestivityId id) {
		this.id = id;
	}

}
