package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CattleDetails generated by hbm2java
 */
@Entity
@Table(name = "cattle_details", catalog = "farm")
public class CattleDetails implements java.io.Serializable {

	private Integer no;
	private Typecow typecow;
	private String CName;
	private String CBirth;
	private String CAge;
	private String CSex;
	private String CColor;
	private String CGen;
	private String CPic;
	private String father;
	private String mother;
	private String devoloper;
	private Integer memberId;
	private Set<CattleShows> cattleShowses = new HashSet<CattleShows>(0);
	private Set<CattleAuctionpun> cattleAuctionpuns = new HashSet<CattleAuctionpun>(0);
	private Set<CattleAuctionkokun> cattleAuctionkokuns = new HashSet<CattleAuctionkokun>(0);

	public CattleDetails() {
	}

	public CattleDetails(Typecow typecow, String CName, String CBirth, String CAge, String CSex, String CColor,
			String CGen, String CPic, String father, String mother,String devoloper, Integer memberId, Set<CattleShows> cattleShowses,
			Set<CattleAuctionpun> cattleAuctionpuns, Set<CattleAuctionkokun> cattleAuctionkokuns) {
		this.typecow = typecow;
		this.CName = CName;
		this.CBirth = CBirth;
		this.CAge = CAge;
		this.CSex = CSex;
		this.CColor = CColor;
		this.CGen = CGen;
		this.CPic = CPic;
		this.father = father;
		this.mother = mother;
		this.devoloper = devoloper;
		this.memberId = memberId;
		this.cattleShowses = cattleShowses;
		this.cattleAuctionpuns = cattleAuctionpuns;
		this.cattleAuctionkokuns = cattleAuctionkokuns;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "No", unique = true, nullable = false)
	public Integer getNo() {
		return this.no;
	}

	public void setNo(Integer no) {
		this.no = no;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "c_typeid")
	public Typecow getTypecow() {
		return this.typecow;
	}

	public void setTypecow(Typecow typecow) {
		this.typecow = typecow;
	}

	@Column(name = "c_name", length = 50)
	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	@Column(name = "c_birth", length = 50)
	public String getCBirth() {
		return this.CBirth;
	}

	public void setCBirth(String CBirth) {
		this.CBirth = CBirth;
	}

	@Column(name = "c_age", length = 45)
	public String getCAge() {
		return this.CAge;
	}

	public void setCAge(String CAge) {
		this.CAge = CAge;
	}

	@Column(name = "c_sex", length = 50)
	public String getCSex() {
		return this.CSex;
	}

	public void setCSex(String CSex) {
		this.CSex = CSex;
	}

	@Column(name = "c_color", length = 50)
	public String getCColor() {
		return this.CColor;
	}

	public void setCColor(String CColor) {
		this.CColor = CColor;
	}

	@Column(name = "c_gen", length = 50)
	public String getCGen() {
		return this.CGen;
	}

	public void setCGen(String CGen) {
		this.CGen = CGen;
	}

	@Column(name = "c_pic", length = 50)
	public String getCPic() {
		return this.CPic;
	}

	public void setCPic(String CPic) {
		this.CPic = CPic;
	}

	@Column(name = "father", length = 45)
	public String getFather() {
		return this.father;
	}

	public void setFather(String father) {
		this.father = father;
	}

	@Column(name = "mother", length = 45)
	public String getMother() {
		return this.mother;
	}
	
	public void setMother(String mother) {
		this.mother = mother;
	}
	
	@Column(name = "devoloper", length = 50)
	public String getDevoloper() {
		return this.devoloper;
	}	
	
	public void setDevoloper(String devoloper) {
		this.devoloper = devoloper;
	}

	@Column(name = "member_id")
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cattleDetails")
	public Set<CattleShows> getCattleShowses() {
		return this.cattleShowses;
	}

	public void setCattleShowses(Set<CattleShows> cattleShowses) {
		this.cattleShowses = cattleShowses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cattleDetails")
	public Set<CattleAuctionpun> getCattleAuctionpuns() {
		return this.cattleAuctionpuns;
	}

	public void setCattleAuctionpuns(Set<CattleAuctionpun> cattleAuctionpuns) {
		this.cattleAuctionpuns = cattleAuctionpuns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cattleDetails")
	public Set<CattleAuctionkokun> getCattleAuctionkokuns() {
		return this.cattleAuctionkokuns;
	}

	public void setCattleAuctionkokuns(Set<CattleAuctionkokun> cattleAuctionkokuns) {
		this.cattleAuctionkokuns = cattleAuctionkokuns;
	}

}
