package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CattleAuctionpunHasFestivityId generated by hbm2java
 */
@Embeddable
public class CattleAuctionpunHasFestivityId implements java.io.Serializable {

	private int cattleAuctionpunNo;
	private int festivityNo;

	public CattleAuctionpunHasFestivityId() {
	}

	public CattleAuctionpunHasFestivityId(int cattleAuctionpunNo, int festivityNo) {
		this.cattleAuctionpunNo = cattleAuctionpunNo;
		this.festivityNo = festivityNo;
	}

	@Column(name = "cattle_auctionpun_No", nullable = false)
	public int getCattleAuctionpunNo() {
		return this.cattleAuctionpunNo;
	}

	public void setCattleAuctionpunNo(int cattleAuctionpunNo) {
		this.cattleAuctionpunNo = cattleAuctionpunNo;
	}

	@Column(name = "festivity_No", nullable = false)
	public int getFestivityNo() {
		return this.festivityNo;
	}

	public void setFestivityNo(int festivityNo) {
		this.festivityNo = festivityNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CattleAuctionpunHasFestivityId))
			return false;
		CattleAuctionpunHasFestivityId castOther = (CattleAuctionpunHasFestivityId) other;

		return (this.getCattleAuctionpunNo() == castOther.getCattleAuctionpunNo())
				&& (this.getFestivityNo() == castOther.getFestivityNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCattleAuctionpunNo();
		result = 37 * result + this.getFestivityNo();
		return result;
	}

}
