package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CattleShowsHasFestivity generated by hbm2java
 */
@Entity
@Table(name = "cattle_shows_has_festivity", catalog = "farm")
public class CattleShowsHasFestivity implements java.io.Serializable {

	private CattleShowsHasFestivityId id;

	public CattleShowsHasFestivity() {
	}

	public CattleShowsHasFestivity(CattleShowsHasFestivityId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cattleShowsNo", column = @Column(name = "cattle_shows_No", nullable = false)),
			@AttributeOverride(name = "festivityNo", column = @Column(name = "festivity_No", nullable = false)) })
	public CattleShowsHasFestivityId getId() {
		return this.id;
	}

	public void setId(CattleShowsHasFestivityId id) {
		this.id = id;
	}

}
