package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CattleShows generated by hbm2java
 */
@Entity
@Table(name = "cattle_shows", catalog = "farm")
public class CattleShows implements java.io.Serializable {

	private Integer no;
	private CattleDetails cattleDetails;
	private String CId;
	private String CSpecies;
	private String CHis;

	public CattleShows() {
	}

	public CattleShows(CattleDetails cattleDetails, String CId, String CSpecies, String CHis) {
		this.cattleDetails = cattleDetails;
		this.CId = CId;
		this.CSpecies = CSpecies;
		this.CHis = CHis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "No", unique = true, nullable = false)
	public Integer getNo() {
		return this.no;
	}

	public void setNo(Integer no) {
		this.no = no;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cattle_details_No")
	public CattleDetails getCattleDetails() {
		return this.cattleDetails;
	}

	public void setCattleDetails(CattleDetails cattleDetails) {
		this.cattleDetails = cattleDetails;
	}

	@Column(name = "c_id", length = 50)
	public String getCId() {
		return this.CId;
	}

	public void setCId(String CId) {
		this.CId = CId;
	}

	@Column(name = "c_species", length = 50)
	public String getCSpecies() {
		return this.CSpecies;
	}

	public void setCSpecies(String CSpecies) {
		this.CSpecies = CSpecies;
	}

	@Column(name = "c_his", length = 45)
	public String getCHis() {
		return this.CHis;
	}

	public void setCHis(String CHis) {
		this.CHis = CHis;
	}

}
