package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CattleAuctionkokun generated by hbm2java
 */
@Entity
@Table(name = "cattle_auctionkokun", catalog = "farm")
public class CattleAuctionkokun implements java.io.Serializable {

	private Integer no;
	private CattleDetails cattleDetails;
	private Integer CNum;
	private Integer CLot;
	private Float CWeigth;
	private String CPic;
	private String SPrice;
	private int festivityNo;

	public CattleAuctionkokun() {
	}

	public CattleAuctionkokun(CattleDetails cattleDetails, int festivityNo) {
		this.cattleDetails = cattleDetails;
		this.festivityNo = festivityNo;
	}

	public CattleAuctionkokun(CattleDetails cattleDetails, Integer CNum, Integer CLot, Float CWeigth, String CPic,
			String SPrice, int festivityNo) {
		this.cattleDetails = cattleDetails;
		this.CNum = CNum;
		this.CLot = CLot;
		this.CWeigth = CWeigth;
		this.CPic = CPic;
		this.SPrice = SPrice;
		this.festivityNo = festivityNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "No", unique = true, nullable = false)
	public Integer getNo() {
		return this.no;
	}

	public void setNo(Integer no) {
		this.no = no;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cattle_details_No", nullable = false)
	public CattleDetails getCattleDetails() {
		return this.cattleDetails;
	}

	public void setCattleDetails(CattleDetails cattleDetails) {
		this.cattleDetails = cattleDetails;
	}

	@Column(name = "c_num")
	public Integer getCNum() {
		return this.CNum;
	}

	public void setCNum(Integer CNum) {
		this.CNum = CNum;
	}

	@Column(name = "c_lot")
	public Integer getCLot() {
		return this.CLot;
	}

	public void setCLot(Integer CLot) {
		this.CLot = CLot;
	}

	@Column(name = "c_weigth", precision = 12, scale = 0)
	public Float getCWeigth() {
		return this.CWeigth;
	}

	public void setCWeigth(Float CWeigth) {
		this.CWeigth = CWeigth;
	}

	@Column(name = "c_pic", length = 50)
	public String getCPic() {
		return this.CPic;
	}

	public void setCPic(String CPic) {
		this.CPic = CPic;
	}

	@Column(name = "s_price", length = 45)
	public String getSPrice() {
		return this.SPrice;
	}

	public void setSPrice(String SPrice) {
		this.SPrice = SPrice;
	}

	@Column(name = "festivity_No", nullable = false)
	public int getFestivityNo() {
		return this.festivityNo;
	}

	public void setFestivityNo(int festivityNo) {
		this.festivityNo = festivityNo;
	}

}
