package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ColorType generated by hbm2java
 */
@Entity
@Table(name = "color_type", catalog = "farm")
public class ColorType implements java.io.Serializable {

	private Integer idcolor;
	private String colorName;
	private Integer cattleDetailsNo;

	public ColorType() {
	}

	public ColorType(String colorName, Integer cattleDetailsNo) {
		this.colorName = colorName;
		this.cattleDetailsNo = cattleDetailsNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcolor", unique = true, nullable = false)
	public Integer getIdcolor() {
		return this.idcolor;
	}

	public void setIdcolor(Integer idcolor) {
		this.idcolor = idcolor;
	}

	@Column(name = "color_name", length = 45)
	public String getColorName() {
		return this.colorName;
	}

	public void setColorName(String colorName) {
		this.colorName = colorName;
	}

	@Column(name = "cattle_details_No")
	public Integer getCattleDetailsNo() {
		return this.cattleDetailsNo;
	}

	public void setCattleDetailsNo(Integer cattleDetailsNo) {
		this.cattleDetailsNo = cattleDetailsNo;
	}

}
