package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Festivity generated by hbm2java
 */
@Entity
@Table(name = "festivity", catalog = "farm")
public class Festivity implements java.io.Serializable {

	private Integer no;
	private Type type;
	private String title;
	private String gene;
	private Date SWork;
	private Date EWork;
	private Date SData;
	private Date EData;
	private String logo;
	private String poster;
	private String details;
	private String location;
	private Integer memberId;

	public Festivity() {
	}

	public Festivity(Type type, String title, String gene, Date SWork, Date EWork, Date SData, Date EData, String logo,
			String poster, String details, String location, Integer memberId) {
		this.type = type;
		this.title = title;
		this.gene = gene;
		this.SWork = SWork;
		this.EWork = EWork;
		this.SData = SData;
		this.EData = EData;
		this.logo = logo;
		this.poster = poster;
		this.details = details;
		this.location = location;
		this.memberId = memberId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "No", unique = true, nullable = false)
	public Integer getNo() {
		return this.no;
	}

	public void setNo(Integer no) {
		this.no = no;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "gene", length = 50)
	public String getGene() {
		return this.gene;
	}

	public void setGene(String gene) {
		this.gene = gene;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "s_work", length = 10)
	public Date getSWork() {
		return this.SWork;
	}

	public void setSWork(Date SWork) {
		this.SWork = SWork;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e_work", length = 10)
	public Date getEWork() {
		return this.EWork;
	}

	public void setEWork(Date EWork) {
		this.EWork = EWork;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "s_data", length = 10)
	public Date getSData() {
		return this.SData;
	}

	public void setSData(Date SData) {
		this.SData = SData;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "e_data", length = 10)
	public Date getEData() {
		return this.EData;
	}

	public void setEData(Date EData) {
		this.EData = EData;
	}

	@Column(name = "logo", length = 50)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "poster", length = 50)
	public String getPoster() {
		return this.poster;
	}

	public void setPoster(String poster) {
		this.poster = poster;
	}

	@Column(name = "details", length = 200)
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	@Column(name = "location", length = 200)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "member_id")
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

}
