package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GenType generated by hbm2java
 */
@Entity
@Table(name = "gen_type", catalog = "farm")
public class GenType implements java.io.Serializable {

	private Integer idgen;
	private String genName;
	private Integer cattleDetailsNo;

	public GenType() {
	}

	public GenType(String genName, Integer cattleDetailsNo) {
		this.genName = genName;
		this.cattleDetailsNo = cattleDetailsNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idgen", unique = true, nullable = false)
	public Integer getIdgen() {
		return this.idgen;
	}

	public void setIdgen(Integer idgen) {
		this.idgen = idgen;
	}

	@Column(name = "gen_name", length = 45)
	public String getGenName() {
		return this.genName;
	}

	public void setGenName(String genName) {
		this.genName = genName;
	}

	@Column(name = "cattle_details_No")
	public Integer getCattleDetailsNo() {
		return this.cattleDetailsNo;
	}

	public void setCattleDetailsNo(Integer cattleDetailsNo) {
		this.cattleDetailsNo = cattleDetailsNo;
	}

}
