package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Intimation generated by hbm2java
 */
@Entity
@Table(name = "intimation", catalog = "farm")
public class Intimation implements java.io.Serializable {

	private Integer id;
	private String title;
	private Date dataTime;
	private String detail;
	private Integer memberId;
	private Integer festivityNo;

	public Intimation() {
	}

	public Intimation(String title, Date dataTime, String detail, Integer memberId, Integer festivityNo) {
		this.title = title;
		this.dataTime = dataTime;
		this.detail = detail;
		this.memberId = memberId;
		this.festivityNo = festivityNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_time", length = 19)
	public Date getDataTime() {
		return this.dataTime;
	}

	public void setDataTime(Date dataTime) {
		this.dataTime = dataTime;
	}

	@Column(name = "detail", length = 45)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "member_id")
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	@Column(name = "festivity_No")
	public Integer getFestivityNo() {
		return this.festivityNo;
	}

	public void setFestivityNo(Integer festivityNo) {
		this.festivityNo = festivityNo;
	}

}
