package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "member", catalog = "farm")
public class Member implements java.io.Serializable {

	private Integer id;
	private StatusNo statusNo;
	private String user;
	private String pass;
	private String email;
	private String idcard;
	private String name;
	private String surname;
	private String address;
	private Integer farm;
	private String tel;

	public Member() {
	}

	public Member(StatusNo statusNo) {
		this.statusNo = statusNo;
	}

	public Member(StatusNo statusNo, String user, String pass, String email, String idcard, String name,
			String surname, String address, Integer farm, String tel) {
		this.statusNo = statusNo;
		this.user = user;
		this.pass = pass;
		this.email = email;
		this.idcard = idcard;
		this.name = name;
		this.surname = surname;
		this.address = address;
		this.farm = farm;
		this.tel = tel;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status", nullable = false)
	public StatusNo getStatusNo() {
		return this.statusNo;
	}

	public void setStatusNo(StatusNo statusNo) {
		this.statusNo = statusNo;
	}

	@Column(name = "user", length = 50)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "pass", length = 50)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "idcard", length = 45)
	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", length = 50)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "address", length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "farm")
	public Integer getFarm() {
		return this.farm;
	}

	public void setFarm(Integer farm) {
		this.farm = farm;
	}

	@Column(name = "tel", length = 50)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

}
