package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pay generated by hbm2java
 */
@Entity
@Table(name = "pay", catalog = "farm")
public class Pay implements java.io.Serializable {

	private Integer id;
	private Float processingfee;
	private String signsauction;
	private Integer worktogetherId;

	public Pay() {
	}

	public Pay(Float processingfee, String signsauction, Integer worktogetherId) {
		this.processingfee = processingfee;
		this.signsauction = signsauction;
		this.worktogetherId = worktogetherId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "processingfee", precision = 12, scale = 0)
	public Float getProcessingfee() {
		return this.processingfee;
	}

	public void setProcessingfee(Float processingfee) {
		this.processingfee = processingfee;
	}

	@Column(name = "signsauction", length = 45)
	public String getSignsauction() {
		return this.signsauction;
	}

	public void setSignsauction(String signsauction) {
		this.signsauction = signsauction;
	}

	@Column(name = "worktogether_id")
	public Integer getWorktogetherId() {
		return this.worktogetherId;
	}

	public void setWorktogetherId(Integer worktogetherId) {
		this.worktogetherId = worktogetherId;
	}

}
