package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatusNo generated by hbm2java
 */
@Entity
@Table(name = "status_no", catalog = "farm")
public class StatusNo implements java.io.Serializable {

	private Integer idstatusNo;
	private String statusName;
	private Set<Member> members = new HashSet<Member>(0);

	public StatusNo() {
	}

	public StatusNo(String statusName, Set<Member> members) {
		this.statusName = statusName;
		this.members = members;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idstatus_no", unique = true, nullable = false)
	public Integer getIdstatusNo() {
		return this.idstatusNo;
	}

	public void setIdstatusNo(Integer idstatusNo) {
		this.idstatusNo = idstatusNo;
	}

	@Column(name = "status_name", length = 45)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusNo")
	public Set<Member> getMembers() {
		return this.members;
	}

	public void setMembers(Set<Member> members) {
		this.members = members;
	}

}
