package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typecow generated by hbm2java
 */
@Entity
@Table(name = "typecow", catalog = "farm")
public class Typecow implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<CattleDetails> cattleDetailses = new HashSet<CattleDetails>(0);

	public Typecow() {
	}

	public Typecow(String name, Set<CattleDetails> cattleDetailses) {
		this.name = name;
		this.cattleDetailses = cattleDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typecow")
	public Set<CattleDetails> getCattleDetailses() {
		return this.cattleDetailses;
	}

	public void setCattleDetailses(Set<CattleDetails> cattleDetailses) {
		this.cattleDetailses = cattleDetailses;
	}

}
