package csa.spring.model;

// Generated May 31, 2015 12:54:58 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Worktogether generated by hbm2java
 */
@Entity
@Table(name = "worktogether", catalog = "farm")
public class Worktogether implements java.io.Serializable {

	private Integer id;
	private String name;
	private String surname;
	private String idcard;
	private String address;
	private Integer festivityNo;

	public Worktogether() {
	}

	public Worktogether(String name, String surname, String idcard, String address, Integer festivityNo) {
		this.name = name;
		this.surname = surname;
		this.idcard = idcard;
		this.address = address;
		this.festivityNo = festivityNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", length = 45)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "idcard", length = 45)
	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "festivity_No")
	public Integer getFestivityNo() {
		return this.festivityNo;
	}

	public void setFestivityNo(Integer festivityNo) {
		this.festivityNo = festivityNo;
	}

}
